### ISSUE TITLE
Option to self host images or host them on ssl

### ISSUE THREAD

**Issue by sunehs** [elmadev/recplayer-react#1]
The images loaded from http://www.recsource.tv/images breaks SSL if you're using that. Would be nice with an option to specifiy the url for self hosting it, or host them on SSL. Alternatively include them in the package.

**Comment by ville-j** [comment]
Not liking the idea of including the images in the package for obvious reasons.. but implementing image loading from a custom url is trivial so I will do that.

**Comment by ville-j** [comment]
This is now implemented on v1.0.4.
