### ISSUE TITLE
onPlay prop vs. wakeLock

### ISSUE THREAD

**Issue by sunehs** [elmadev/recplayer-react#16]
Preventing screen sleep during rec playback was suggested over on elmaonline-site https://github.com/elmadev/elmaonline-site/issues/558 but I realised we can't implement that since only inside recplayer-react do you know if rec is currently playing or not. So as I see it the options are to either implement an onPlay callback prop or implement wakeLock in recplayer-react, but not sure what makes most sense. Any thoughts?

**Comment by PabloCorso** [comment]
Yes that was my concern with recplayer. A sort of on change callback could be enough to do wakelock on and off. No much experience with that but sounds like a good solution.

**Comment by ville-j** [comment]
Might make sense to implement the wakelock in recplayer code since it is useful in all projects that might use the recplayer. Not that there are many active projects using it atm, but for the future also. Perhaps a wakelock boolean property on the component would be good.

**Comment by Ben3eeE** [comment]
Why not both :bear:

**Comment by sunehs** [comment]
Haven't started, but did make a hook for it on eol site before I realized I couldn't use it. I know recplayer can't use that currently, but maybe there's some helpful bits in it: https://pastebin.com/TuQT0p4m

**Comment by ville-j** [comment]
There is now an open PR #17 if someone wants to test it or add anything.
